#!/bin/sh

# enable port I/O from userspace for NYX hypercalls, then re-exec this script
if [ "$PORTIO_ENABLED" != "1" ]; then
  export PORTIO_ENABLED=1
  exec /portio-enable /init
fi

mount -t proc none /proc
mount -t sysfs none /sys
mount -t debugfs none /sys/kernel/debug
mount -t devtmpfs none /dev
mount -t tmpfs none /tmp
chmod 777 / /tmp

chmod +x /loader

echo "7" > /proc/sys/kernel/printk
echo "0" >  /proc/sys/kernel/printk_ratelimit 
echo "19999999" >  /proc/sys/kernel/printk_ratelimit_burst
echo "1" > /proc/sys/kernel/panic_on_oops

mkdir -p /home/ubuntu/
addgroup ubuntu
adduser --gecos "ubuntu" --disabled-password --ingroup ubuntu ubuntu
echo "ubuntu:ubuntu" | chpasswd

# multiarch support
export LD_LIBRARY_PATH=/lib32

START
#./loader
#sh
